---
layout: cv
title: Shinesaikhan Ganbold's CV
---
# Shinesaikhan Ganbold

### Contact Informations

- shinesaihan238@gmail.com
- (986)275 63-76
- [LinkedIn](https://www.linkedin.com/in/shinegan/)


## Currently

Student in BYU-Idaho

### Specializing in

Data Science, Statistics, Machine Learning

## Education

__Brigham Young University - Idaho.__
`December 2028`

## Projects

Titanic Survival Prediction, *Data Science Society*, Rexburg, ID
`April 2025 - July 2025`

- Built a logistic regression model to predict passenger survival on the Titanic dataset using Python
- Engineered new features (e.g., family size, passenger class) to improve model accuracy by ~8%

## Work Experience

__Server in Clubhouse Karaoke__, Mongolia
`November 2024 - March 2025`

- Coordinated event logistics for 100+ client celebrations monthly, optimizing table assignments and service flow to improve customer satisfaction and reduce setup time by 15%

- Maintained service quality for 50+ daily guests by tracking table status, supervising requests efficiently, and collaborating closely with team members to ensure a consistent customer experience

__Server in GrandLux Restaurant__, Mongolia
`September 2023 - April 2024`

- Handled multiple shifts and supported team operations for 12 tables, maintaining service and cleanliness standards

- Trained and mentored a new server on restaurant standards, POS system, and customer service techniques, improving team efficiency and reducing order errors during peak hours

- Provided attentive, personalized service, contributing to a 95% satisfaction rating on guest surveys

__Warehouse assistant in CU (convenience store)__, Mongolia
`May 2022 - August 2022`

- Organized and tracked inventory for 140+ branch stores; ensured accurate order collection and shipment

- Operated heavy equipment safely and efficiently in a fast-paced warehouse environment for over 1000+ orders

## Key Skills 

- Programming Languages: Python, R, SQL
- Data Science & Machine Learning: Pandas, NumPy, Matplotlib, Data Cleaning, Feature Engineering, Regression Model, Machine Learning Basics
- Database Management: MySQL, SQLite (basic query writing, joins, and data extraction)
- Other Skills: Attention to Detail, Team Collaboration, Time Management, Communication, Hypothesis Testing, Correlation Analysis, Descriptive Statistics, Probability

<!-- ### Footer

Last updated: May 2013 -->